In [1]:
import numpy as np
a = np.array([1, 2, 3, 4])      # 리스트 → 배열
print(a, type(a))
print(np.zeros(3))              # 0으로 채운 배열
print(np.ones(3))              # 1로 채운 배열
print(np.arange(0, 10, 2))     # 0~10 미만, 2씩

[1 2 3 4] <class 'numpy.ndarray'>
[0. 0. 0.]
[1. 1. 1.]
[0 2 4 6 8]


In [2]:
a = np.array([1, 2, 3, 4])
print('shape:', a.shape)   # (4,)
print('ndim :', a.ndim)    # 1차원
print('dtype:', a.dtype)   # 데이터 타입

shape: (4,)
ndim : 1
dtype: int64


In [3]:
a = np.array([10, 20, 30, 40, 50])
print(a[0])      # 10
print(a[-1])     # 50
print(a[1:4])    # [20 30 40]

10
50
[20 30 40]


In [4]:
m = np.array([[1, 2, 3],
              [4, 5, 6]])
print('shape:', m.shape)   # (2, 3) = 2행 3열
print('첫 행 :', m[0])      # [1 2 3]
print('[0,2]:', m[0, 2])   # 3 (0행 2열)
print('1번 열:', m[:, 1])   # [2 5]  ← 모든 행의 1번 열
# ML 예: pred[:, 1] → 예측확률에서 '1(양성)일 확률' 열만 뽑기

shape: (2, 3)
첫 행 : [1 2 3]
[0,2]: 3
1번 열: [2 5]


In [5]:
a = np.array([1, 2, 3, 4])
print(a * 2)        # [2 4 6 8]   각 원소에 곱
print(a + 10)       # [11 12 13 14]
print(a + a)        # [2 4 6 8]   같은 위치끼리
print(a.mean())     # 평균

[2 4 6 8]
[11 12 13 14]
[2 4 6 8]
2.5


In [6]:
a = np.array([10, 25, 30, 5, 40])
print(a > 20)          # [False  True  True False  True]
print(a[a > 20])       # [25 30 40]  ← 조건 True인 값만

[False  True  True False  True]
[25 30 40]


In [7]:
m = np.array([[1, 2, 3],
              [4, 5, 6]])
print('전체 합 :', m.sum())
print('열별 합 :', m.sum(axis=0))   # [5 7 9]  세로로
print('행별 합 :', m.sum(axis=1))   # [6 15]   가로로
print('평균/최대/표준편차:', m.mean(), m.max(), round(m.std(), 2))

전체 합 : 21
열별 합 : [5 7 9]
행별 합 : [ 6 15]
평균/최대/표준편차: 3.5 6 1.71


In [10]:
a = np.arange(6)           # [0 1 2 3 4 5]
print("--")
print(a.reshape(2, 3))     # 2행 3열
print("--")
print(a.reshape(3, 2))     # 3행 2열
print("--")
print(a.reshape(-1, 1))    # -1 = 자동 계산 (여기선 6행 1열)

--
[[0 1 2]
 [3 4 5]]
--
[[0 1]
 [2 3]
 [4 5]]
--
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
